flowchart LR
  オートメーション一覧["# オートメーション一覧"]
  subgraph オートメーション作成ウィザード_group["# オートメーション作成ウィザード"]
    オートメーション作成ウィザード_トリガー選択["## トリガー選択"]
    オートメーション作成ウィザード_アクション選択["## アクション選択"]
    オートメーション作成ウィザード_確認["## 確認"]
  end

  オートメーション一覧 -->|"タップ(作成ボタン)"| オートメーション作成ウィザード_トリガー選択
  オートメーション作成ウィザード_トリガー選択 -->|"タップ(キャンセルボタン)"| オートメーション一覧
  オートメーション作成ウィザード_トリガー選択 -->|"タップ(トリガー候補一覧)"| オートメーション作成ウィザード_アクション選択
  オートメーション作成ウィザード_アクション選択 -->|"タップ(キャンセルボタン)"| オートメーション一覧
  オートメーション作成ウィザード_アクション選択 -->|"タップ(アクション候補一覧)"| オートメーション作成ウィザード_確認
  オートメーション作成ウィザード_アクション選択 -->|"タップ(戻るボタン)"| オートメーション作成ウィザード_トリガー選択
  オートメーション作成ウィザード_確認 -->|"タップ(キャンセルボタン)"| オートメーション一覧
  オートメーション作成ウィザード_確認 -->|"タップ(戻るボタン)"| オートメーション作成ウィザード_アクション選択
  オートメーション作成ウィザード_確認 -->|"タップ(完了ボタン)"| オートメーション一覧
