flowchart LR
  subgraph リビング照明_group["# リビング照明"]
    リビング照明_オンライン["## オンライン"]
    リビング照明_オフライン["## オフライン"]
  end
  subgraph リビングエアコン_group["# リビングエアコン"]
    リビングエアコン_オンライン["## オンライン"]
    リビングエアコン_オフライン["## オフライン"]
  end
  subgraph 寝室ドア鍵_group["# 寝室ドア鍵"]
    寝室ドア鍵_オンライン["## オンライン"]
    寝室ドア鍵_オフライン["## オフライン"]
  end

  リビング照明_オンライン -->|"タップ(オートメーションを作成)"| automation__オートメーション作成ウィザード
