flowchart LR
  起動["# 起動"]
  subgraph セキュリティバナー_group["# セキュリティバナー"]
    セキュリティバナー_在宅["## 在宅"]
    セキュリティバナー_外出["## 外出"]
    セキュリティバナー_就寝["## 就寝"]
  end
  モード切替["# モード切替"]
  subgraph ホーム_group["# ホーム"]
    ホーム_通常["## 通常"]
    ホーム_就寝中["## 就寝中"]
  end
  リビング["# リビング"]
  寝室["# 寝室"]
  設定["# 設定"]

  起動 -->|"起動"| ホーム_通常
  セキュリティバナー_在宅 -->|"タップ(バナー)"| モード切替
  セキュリティバナー_外出 -->|"タップ(バナー)"| モード切替
  セキュリティバナー_就寝 -->|"タップ(バナー)"| モード切替
  ホーム_通常 -->|"タップ(リビング)"| リビング
  ホーム_通常 -->|"タップ(寝室)"| 寝室
  ホーム_通常 -->|"タップ(設定)"| 設定
  ホーム_通常 -->|"タップ(オートメーション)"| automation__オートメーション一覧
  ホーム_就寝中 -->|"タップ(リビング)"| リビング
  ホーム_就寝中 -->|"タップ(寝室)"| 寝室
  ホーム_就寝中 -->|"タップ(設定)"| 設定
  ホーム_就寝中 -->|"タップ(オートメーション)"| automation__オートメーション一覧
  ホーム_就寝中 -->|"タップ(おやすみ解除ボタン)"| ホーム_通常
  リビング -->|"タップ(リビング照明)"| devices__リビング照明
  リビング -->|"タップ(リビングエアコン)"| devices__リビングエアコン
  寝室 -->|"タップ(寝室ドア鍵)"| devices__寝室ドア鍵
