flowchart LR
  出品開始["# 出品開始"]
  商品情報入力["# 商品情報入力"]
  カテゴリ一覧["# カテゴリ一覧"]
  価格設定["# 価格設定"]
  出品完了["# 出品完了"]

  出品開始 -->|"タップ(撮影ボタン)"| 商品情報入力
  出品開始 -->|"タップ(アルバムから選ぶ)"| 商品情報入力
  商品情報入力 -->|"タップ(カテゴリ選択)"| カテゴリ一覧
  商品情報入力 -->|"タップ(次へ)"| 価格設定
  価格設定 -->|"[成功]タップ(出品する)"| 出品完了
