flowchart LR
  起動["# 起動"]
  タブバー["# タブバー"]
  ホーム["# ホーム"]
  検索["# 検索"]
  subgraph お知らせ_group["# お知らせ"]
    お知らせ_未読なし["## 未読なし"]
    お知らせ_未読あり["## 未読あり"]
  end
  マイページ["# マイページ"]

  起動 -->|"起動"| ホーム
  タブバー -->|"タップ(ホームタブ)"| ホーム
  タブバー -->|"タップ(お知らせタブ)"| お知らせ_未読なし
  タブバー -->|"タップ(出品タブ)"| listing__出品開始
  タブバー -->|"タップ(マイページタブ)"| マイページ
  ホーム -->|"タップ(検索バー)"| 検索
  お知らせ_未読なし -->|"タップ(お知らせ行)"| trade__取引
  お知らせ_未読あり -->|"タップ(お知らせ行)"| trade__取引
  お知らせ_未読あり -->|"画面が表示される"| お知らせ_未読なし
  マイページ -->|"タップ(出品した商品)"| trade__商品詳細
  マイページ -->|"タップ(購入した商品)"| trade__取引
