flowchart LR
  subgraph 商品カード_group["# 商品カード"]
    商品カード_販売中["## 販売中"]
    商品カード_SOLD["## SOLD"]
  end
  subgraph 商品詳細_group["# 商品詳細"]
    商品詳細_販売中["## 販売中"]
    商品詳細_SOLD["## SOLD"]
  end
  subgraph いいねボタン_group["# いいねボタン"]
    いいねボタン_未いいね["## 未いいね"]
    いいねボタン_いいね済["## いいね済"]
  end
  購入確認["# 購入確認"]
  支払い方法選択["# 支払い方法選択"]
  購入完了["# 購入完了"]
  subgraph 取引_group["# 取引"]
    取引_取引中["## 取引中"]
    取引_発送済["## 発送済"]
    取引_評価中["## 評価中"]
    取引_取引完了["## 取引完了"]
  end

  商品カード_販売中 -->|"タップ(本体)"| 商品詳細_販売中
  商品カード_SOLD -->|"タップ(本体)"| 商品詳細_販売中
  商品詳細_販売中 -->|"タップ(購入ボタン)"| 購入確認
  いいねボタン_未いいね -->|"タップ(ハート)"| いいねボタン_いいね済
  いいねボタン_いいね済 -->|"タップ(塗りハート)"| いいねボタン_未いいね
  購入確認 -->|"タップ(支払い方法)"| 支払い方法選択
  購入確認 -->|"[成功]タップ(購入を確定する)"| 購入完了
  購入完了 -->|"タップ(取引画面へ)"| 取引_取引中
  取引_取引中 -->|"商品が発送される"| 取引_発送済
  取引_発送済 -->|"タップ(受取評価ボタン)"| 取引_評価中
  取引_評価中 -->|"タップ(良いボタン)"| 取引_取引完了
  取引_評価中 -->|"タップ(悪いボタン)"| 取引_取引完了
